src/com/ametis/cms/web/form/RejectedClaimForm.java
package com.ametis.cms.web.form;

import com.ametis.cms.datamodel.Claim;
import com.ametis.cms.datamodel.RejectCategory;
import com.ametis.cms.datamodel.RejectedClaim;
import com.ametis.cms.util.StringUtil;

// imports- 

/**
 * RejectedClaim is a mapping of rejected_claim Table.
*/
public class RejectedClaimForm implements java.io.Serializable
// extends+ 

// extends- 
{


	private boolean isNewRejectedClaim = false;
	private RejectedClaim rejectedClaimBean ;
	private String claimNumber;
	
	/*
		<form>Bean merupakan representasi dari "SINGLE" table dan
		misalkan ada form2 yang merupakan referensi dari tabel lain
		bikin aja field2 bean yang mengacu ke referensi itu
		biar nanti automatic loading

	*/

    public RejectedClaimForm()
    {
    	this.rejectedClaimBean = new RejectedClaim();
    	this.isNewRejectedClaim = true;
    }
    public RejectedClaimForm (RejectedClaim object){
		this.rejectedClaimBean = object;
    }
    public boolean isNewRejectedClaim (){

    	return this.isNewRejectedClaim;
    }
	public RejectedClaim getRejectedClaim (){
		return this.rejectedClaimBean ;
	}
	public void setRejectedClaim (RejectedClaim object){
		this.rejectedClaimBean = object;
	}

			
	public void setRejectedClaimId(String obj){

		rejectedClaimBean.setRejectedClaimId(StringUtil.getLongValue(obj,0));

	}

	public String getRejectedClaimId(){
		return StringUtil.getStringValue(
		rejectedClaimBean.getRejectedClaimId());

	}
	
				
	public void setClaimId(String obj){

		if (obj != null && !obj.equalsIgnoreCase("")){
			Claim claim = new Claim();
			claim.setClaimId(Integer.valueOf(obj));
			
			rejectedClaimBean.setClaimId(claim);
		}

	}

	public String getClaimId(){
		String result = "";
		
		if (rejectedClaimBean.getClaimId() != null){
			result = rejectedClaimBean.getClaimId().getClaimId().toString();
		}
		return result;

	}
	
				
	public void setRejectionCategory(RejectCategory obj){

		rejectedClaimBean.setRejectionCategory(obj);

	}

	public RejectCategory getRejectionCategory(){
		return 	rejectedClaimBean.getRejectionCategory();

	}
	
					public void setRejectionSubject(String obj){

		rejectedClaimBean.setRejectionSubject(new String(obj));

	}

	public String getRejectionSubject(){
		return StringUtil.getStringValue(
		rejectedClaimBean.getRejectionSubject());

	}
	
					public void setDescription(String obj){

		rejectedClaimBean.setDescription(new String(obj));

	}

	public String getDescription(){
		return StringUtil.getStringValue(
		rejectedClaimBean.getDescription());

	}
	public String getClaimNumber() {
		return claimNumber;
	}
	public void setClaimNumber(String claimNumber) {
		this.claimNumber = claimNumber;
	}
	
				
// class+ 

// class- 
}

src/com/ametis/cms/web/controller/RejectedClaimController.java
package com.ametis.cms.web.controller;

import java.io.IOException;
import java.util.Collection;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.springframework.context.support.ResourceBundleMessageSource;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
import org.springframework.web.servlet.view.RedirectView;

import com.ametis.cms.datamodel.ActionUser;
import com.ametis.cms.datamodel.BatchClaim;
import com.ametis.cms.datamodel.Claim;
import com.ametis.cms.datamodel.Member;
import com.ametis.cms.datamodel.RejectedClaim;
import com.ametis.cms.service.ActivityLogService;
import com.ametis.cms.service.BatchClaimService;
import com.ametis.cms.service.ClaimService;
import com.ametis.cms.service.RejectedClaimService;
import com.ametis.cms.service.SecurityService;
import com.ametis.cms.service.UserService;
import com.ametis.cms.util.CaseReportDownloader;
import com.ametis.cms.util.ClaimDocumentDownloader;
import com.ametis.cms.util.WebUtil;
import com.ametis.cms.util.servlet.TableRenderingServlet;

// imports+ 

// imports- 

/**
 * RejectedClaim is a servlet controller for rejected_claim Table. All you have
 * to do is to convert necessary data field to the named parameter
 */
public class RejectedClaimController implements Controller

// extends+

// extends-

{

	private RejectedClaimService rejectedClaimService;
	private ClaimService claimService;

	private UserService userService;

	private ResourceBundleMessageSource alertProperties;

	private Integer countSet;

	private Integer maxPercountSet;
	private SecurityService securityService;

	private ActivityLogService logService;
	private BatchClaimService batchClaimService;

	
	
	public BatchClaimService getBatchClaimService() {
		return batchClaimService;
	}

	public void setBatchClaimService(BatchClaimService batchClaimService) {
		this.batchClaimService = batchClaimService;
	}

	public ActivityLogService getLogService() {
		return logService;
	}

	public void setLogService(ActivityLogService logService) {
		this.logService = logService;
	}
	public ClaimService getClaimService() {
		return claimService;
	}

	public void setClaimService(ClaimService claimService) {
		this.claimService = claimService;
	}

	public SecurityService getSecurityService() {
		return securityService;
	}

	public void setSecurityService(SecurityService securityService) {
		this.securityService = securityService;
	}

	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	public UserService getUserService() {
		return userService;
	}

	public void setCountSet(Integer countSet) {
		this.countSet = countSet;
	}

	public Integer getCountSet() {
		return this.countSet;
	}

	public void setMaxPercountSet(Integer maxCount) {
		this.maxPercountSet = maxCount;
	}

	public Integer getMaxPercountSet() {
		return this.maxPercountSet;
	}

	public void setAlertProperties(ResourceBundleMessageSource alert) {
		this.alertProperties = alert;
	}

	public ResourceBundleMessageSource getAlertProperties() {
		return alertProperties;
	}

	public void setRejectedClaimService(
			RejectedClaimService rejectedClaimService) {
		this.rejectedClaimService = rejectedClaimService;
	}

	public RejectedClaimService getRejectedClaimService() {
		return this.rejectedClaimService;
	}

	public ModelAndView deletePerformed(HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		ModelAndView result = null;

		try {
			Long rejectedClaimId = WebUtil.getParameterLong(request,
					"rejectedClaimId");

			/*
			 * Pkey ini merupakan representasi dari primary key, misalkan hasil
			 * get dari attribute diatas ^ itu cuma ada 1 key saja berarti
			 * tinggal pkey = <nama var diatas> tapi kalau misalkan composite
			 * primary key berarti tinggal bikin representasi primary key nya
			 * saja .
			 */
			java.io.Serializable pkey = rejectedClaimId;

			ActionUser user= securityService.getActionUser(request); 
			
			boolean isUserAuthorized = securityService.isUserAuthorized(user, "DELETEREJECTEDCLAIM");
			
			if (!isUserAuthorized){
				
				ModelAndView errorResult = new ModelAndView(new RedirectView("errorpage"));	errorResult.addObject("errorType","accessDenied");			
				errorResult.addObject("errorMessage", "You Are Not Authorized for DELETEREJECTEDCLAIM access");
				return errorResult;
				
			}
			RejectedClaim res = rejectedClaimService.delete(pkey, user);

			if (res != null) {
				request.setAttribute("alert", alertProperties.getMessage(
						"success.delete.rejectedclaim", null, "success", Locale
								.getDefault()));
			} else {
				request.setAttribute("alert", alertProperties.getMessage(
						"fail.delete.rejectedclaim", null, "fail", Locale
								.getDefault()));

			}
			result = searchPerformed(request, response, "searchRejectedClaim");
		} catch (Exception e) {
			// nanti kalo sudah OK codenya e.printStackTrace nya di hapus saja
			e.printStackTrace();
			request.setAttribute("alert", alertProperties.getMessage(
					"system.error " + e.getMessage(), null, "fail", Locale
							.getDefault()));
			result = new ModelAndView("error");
		}
		return result;
	}

	public ModelAndView detailPerformed(HttpServletRequest request,
			HttpServletResponse response, String location) throws Exception {
		ModelAndView result = null;

		try {
			Long rejectedClaimId = WebUtil.getParameterLong(request,
					"rejectedClaimId");

			Integer index = WebUtil.getParameterInteger(request, "index");
			String searchtext = WebUtil.getParameterString(request,
					"searchtext", "");
			String searchby = WebUtil.getParameterString(request, "searchby",
					"");
			/*
			 * Pkey ini merupakan representasi dari primary key, misalkan hasil
			 * get dari attribute diatas ^ itu cuma ada 1 key saja berarti
			 * tinggal pkey = <nama var diatas> tapi kalau misalkan composite
			 * primary key berarti tinggal bikin representasi primary key nya
			 * saja .
			 */

			result = new ModelAndView(location);
			java.io.Serializable pkey = rejectedClaimId;
			RejectedClaim object = rejectedClaimService.get(pkey);

			if (object == null) {
				request.setAttribute("alert", alertProperties.getMessage(
						"not.found.rejectedclaim", null, "fail", Locale
								.getDefault()));
			}
			/*
			 * convention .. kalo mau nampilkan sebuah object pake BeanClass aja
			 * ya .. ga pake 's' -adhit
			 */

			result.addObject("rejectedClaim", object);
			result.addObject("index", index);
			result.addObject("searchtext", searchtext);
			result.addObject("searchby", searchby);

		} catch (Exception e) {
			e.printStackTrace();
			request.setAttribute("alert", alertProperties.getMessage(
					"system.error " + e.getMessage(), null, "fail", Locale
							.getDefault()));

			result = new ModelAndView("error");
		}

		return result;
	}

	public ModelAndView printPerformed(HttpServletRequest request,
			HttpServletResponse response, String location) throws Exception {
		ModelAndView result = null;

		try {
			
			Long rejectedClaimId = WebUtil.getParameterLong(request,
					"rejectedClaimId");

			Integer claimId = WebUtil.getParameterInteger(request, "claimId");
			
			Integer index = WebUtil.getParameterInteger(request, "index");
			String searchtext = WebUtil.getParameterString(request,
					"searchtext", "");
			String searchby = WebUtil.getParameterString(request, "searchby",
					"");
			/*
			 * Pkey ini merupakan representasi dari primary key, misalkan hasil
			 * get dari attribute diatas ^ itu cuma ada 1 key saja berarti
			 * tinggal pkey = <nama var diatas> tapi kalau misalkan composite
			 * primary key berarti tinggal bikin representasi primary key nya
			 * saja .
			 */

			result = new ModelAndView(location);
			java.io.Serializable pkey = rejectedClaimId;
			
			String[] required = {"Claim.MemberId","Claim.MemberId.ParentMember","Claim.MemberId.MemberGroupId","Claim.MemberId.ClientId","Claim.DiagnosisId"};
			Claim claim = claimService.get(claimId,required);
			
			if (claim != null){
				
				String[] param = {"claimId.claimId"};
				Object[] value = {claim.getClaimId()};
				
				Integer total = rejectedClaimService.getTotal(null,null,param,value);
				Collection<RejectedClaim> rejectedClaims = rejectedClaimService.search(null,null,param,value,0,total);
				
				if (rejectedClaims != null ){
					
					RejectedClaim object = rejectedClaims.iterator().next();
		
					if (object == null) {
						request.setAttribute("alert", alertProperties.getMessage(
								"not.found.rejectedclaim", null, "fail", Locale
										.getDefault()));
					}
				
					
					result.addObject("rejectedClaim", object);
					result.addObject("index", index);
					result.addObject("searchtext", searchtext);
					result.addObject("searchby", searchby);
					
				}
				
				Member policyHolder = claim.getMemberId().getParentMember();
				
				result.addObject("member", claim.getMemberId());
				result.addObject("policyHolder", policyHolder);
				result.addObject("claim", claim);
			}
			

			

		} catch (Exception e) {
			e.printStackTrace();
			request.setAttribute("alert", alertProperties.getMessage(
					"system.error " + e.getMessage(), null, "fail", Locale
							.getDefault()));

			result = new ModelAndView("error");
		}

		return result;
	}
	
	public ModelAndView downloadRejectedClaimPerformed(HttpServletRequest request,
			HttpServletResponse response, String location) throws Exception {
		
		ModelAndView result = null;
		try {
			
			
			
			ActionUser user= securityService.getActionUser(request); 
			
			boolean isUserAuthorized = securityService.isUserAuthorized(user, "SEARCHCASE");
			

WebRoot/WEB-INF/jsp/rejectedClaim/detailRejectedClaim.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core_rt" %>
<%@ taglib prefix="spring" uri="/WEB-INF/spring.tld"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt" %>


<h1>Rejected Claim</h1>

<form action="rejectedclaim" method="GET" name="form1" id="form_layout">

<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr> 
      <td style="padding-bottom: 2px;">        
        <input title="Edit [Alt+Shift+E]" accesskey="E" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:ubah()" name="Edit" value=" Update " type="button">
        <input title="Hapus [Alt+Shift+H]" accesskey="H" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:hapus()" name="Delete" value=" Delete " type="button">        		
		</td>
      <td align="right"></td>
    </tr>
  </tbody>
</table>
<table class="tabDetailView" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td colspan="20"  style="padding: 0px;">
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tbody>
				<tr>
					<td style="text-align: left;" class="tabDetailViewDL">&nbsp;
						<a href="#" onclick='' class="listViewPaginationLinkS1" style="font-weight: normal;">View Change Log</a>
					</td>
					<td class="tabDetailViewDL" align="right" nowrap="nowrap">
						<a href="rejectedclaim?navigation=search&searchtext=<c:out value="${searchtext}"/>&searchby=<c:out value="${searchby}" />&rowset=<c:out value="${rowser}" />&index=<c:out value="${index}"/>" class="tabDetailViewDFLink" style="font-weight: normal;">Return to List&nbsp;</a>					
					</td>
				</tr>
			</tbody>
		</table>
	  </td>
    </tr>
	<input type="hidden" name="navigation" value="">
	<input type="hidden" name="rejectedClaimId" value="<c:out value="${rejectedClaim.rejectedClaimId}" />">
	
	
		
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Claim Id :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.claimId}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Rejection Category :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.rejectionCategory}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Rejection Subject :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.rejectionSubject}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Description :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.description}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Created Time :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.createdTime}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Updated Time :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.updatedTime}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Created By :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.createdBy}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Updated By :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.updatedBy}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Deleted Time :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.deletedTime}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Deleted By :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.deletedBy}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Deleted Status :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${rejectedClaim.deletedStatus}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	    </tr>
				
	</tbody>
</table>

	<h2>Foreign Affair</h2>

		<center>
		<input type="button" class="btn_back" name="balik" value="Back" onclick="javascript:kembali()">
		<input type="button" class="btn" name="update" value="Update" onclick="javascript:ubah()">
		<input type="button" class="btn" name="delete" value="Delete" onclick="javascript:hapus()">
	</center>
</form>
<script language="javascript">
	function hapus (){
	var delConfirm = window.confirm ("Are You Sure Want To Delete This Entry ?");
		if (delConfirm){
			document.form1.navigation.value = "delete";
			document.form1.submit();
		}
	}
	function kembali (){
		document.form1.navigation.value = "back";
		document.form1.submit();
	}
	function ubah (){
		document.form1.navigation.value = "update";
		document.form1.action = "rejectedclaim-form";
		document.form1.method = "GET";
		document.form1.submit();
	}
</script>

WebRoot/WEB-INF/jsp/rejectedClaim/editRejectedClaim.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core_rt" %>
<%@ taglib prefix="spring" uri="/WEB-INF/spring.tld"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt" %>


<form action="rejectedclaim-form" method="POST"  name="form1" id="form_layout">


<table class="tabForm" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody>

<tr>
								<td class="dataLabel">
									
								</td>


								<td class="dataField">
									
								</td>
								<td class="dataLabel">
								
								</td>
								<td class="dataField">
									
									
								</td>
							</tr>
<%
String alert = (String) request.getAttribute("alert");
if (alert != null && !alert.trim().equals("")) {%>
	<div id="warning">
		<c:out value="${alert}"></c:out>
	</div>
	<%}%>


	<spring:bind path="rejectedClaimForm.rejectedClaimId">
		<input type="hidden" name="<c:out value="${status.expression}"/>" value="<c:out value="${status.value}" />" >
			<div id="fredcaption">
				<c:out value="${status.errorMessage}" />
			</div>
		</spring:bind>

<input type="hidden" name="navigation" value="">



		<tr>
			<td class="dataLabel"> Claim : </td>				
			
			<td class="dataField">
			<spring:bind path="rejectedClaimForm.claimId">
					<input type="hidden" name="<c:out value="${status.expression}" />" value="<c:out value="${status.value}" />">
				<div id="fredcaption">
					<c:out value="${status.errorMessage}" />
				</div>
			</spring:bind>
			<spring:bind path="rejectedClaimForm.claimNumber">
				<input type="text" size="35" name="<c:out value="${status.expression}" />" value="<c:out value="${status.value}" />">
			</spring:bind>
			</td>
					    		<td class="dataLabel"> Rejection Category : </td>				
			

						<td class="dataField">
			<spring:bind path="rejectedClaimForm.rejectionCategory.rejectCategoryId">
				<select name="<c:out value="${status.expression}" />">
					<c:forEach items="${rejectCategory}" var="reject">
						<option value="<c:out value="${reject.rejectCategoryId}" />" <c:if test="${status.value eq reject.rejectCategoryId}" >selected</c:if> ><c:out value="${reject.rejectCategoryName}" /></option>
					</c:forEach>
				</select>
				<div id="fredcaption">
					<c:out value="${status.errorMessage}" />
				</div>
			</spring:bind>
			</td>
	</tr>
	


			<tr>
			<td class="dataLabel"> Rejection Subject : </td>				
			

			<td class="dataField">
			<spring:bind path="rejectedClaimForm.rejectionSubject">
			<input type="text" size="35" value="<c:out value="${status.value}" />" name="<c:out value="${status.expression}" />" >
				<div id="fredcaption">
					<c:out value="${status.errorMessage}" />
				</div>
			</spring:bind>
			</td>
			
	    <td class="dataLabel"></td>
	    <td class="dataField"></td>
	</tr>



			

			


			

	

			

			<tr>
				<td class="dataLabel"> Description : </td>				
			

		    <td class="dataField" colspan="3">
			<spring:bind path="rejectedClaimForm.description">
			<textarea rows="8" cols="60" name="<c:out value="${status.expression}"/>"><c:out value="${status.value}" /></textarea>
				<div id="fredcaption">
					<c:out value="${status.errorMessage}" />
				</div>
			</spring:bind>
		</td>
	</tr>
		
			<tr>
								<td class="dataLabel">
									
								</td>


								<td class="dataField">
									
								</td>
								<td class="dataLabel">
								
								</td>
								<td class="dataField">
									
									
								</td>
							</tr>
					
	</tbody>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td style="padding-top: 2px;">
	    <input type="hidden" name="notyet" value="">
        <input title="Save [Alt+Shift+S]" accesskey="S" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:simpan()" name="Save" value=" Save " type="submit">
        <input title="Cancel [Alt+Shift+C]" accesskey="C" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:cancel()" name="Cancel" value=" Cancel " type="button">         
	  </td>
      <td align="right"></td>
    </tr>
  </tbody>
</table>
</form>

<script language="javascript">
	function simpan (){

		document.form1.method = "POST";
		document.form1.action = "rejectedclaim-form";
		document.form1.submit();
	}
	function cancel (){
		document.form1.navigation.value = "detail";
		document.form1.action = "claim";
		document.form1.submit();
	}
	// forreign affairs
			// forreign affairs end
</script>