src/com/ametis/cms/web/form/UserForm.java
package com.ametis.cms.web.form;

import com.ametis.cms.datamodel.Role;
import com.ametis.cms.datamodel.SubscriptionStatus;
import com.ametis.cms.datamodel.User;
import com.ametis.cms.util.StringUtil;

// imports- 

/**
 * User is a mapping of user Table.
*/
public class UserForm implements java.io.Serializable
// extends+ 

// extends- 
{


	private boolean isNewUser = false;
	private User userBean ;
	
	private Integer institutionId;
	private String institutionName;
	
	private String password;
	private String confirmPassword;
	/*
		<form>Bean merupakan representasi dari "SINGLE" table dan
		misalkan ada form2 yang merupakan referensi dari tabel lain
		bikin aja field2 bean yang mengacu ke referensi itu
		biar nanti automatic loading

	*/

    public UserForm()
    {
    	this.userBean = new User();
    	this.isNewUser = true;
    }
    public UserForm (User object){
		this.userBean = object;
    }
    public boolean isNewUser (){

    	return this.isNewUser;
    }
	public User getUser (){
		return this.userBean ;
	}
	public void setUser (User object){
		this.userBean = object;
	}

			
	public void setUserId(String obj){

		userBean.setUserId(StringUtil.getIntegerValue(obj,0));

	}

	public String getUserId(){
		return StringUtil.getStringValue(
		userBean.getUserId());

	}
	
					public void setUsername(String obj){

		userBean.setUsername(new String(obj));

	}

	public String getUsername(){
		return StringUtil.getStringValue(
		userBean.getUsername());

	}
	
					public void setPassword(String obj){

		userBean.setPassword(new String(obj));

	}

	public String getPassword(){
		return StringUtil.getStringValue(
		userBean.getPassword());

	}
	
								public void setFirstName(String obj){

		userBean.setFirstName(new String(obj));

	}

	public String getFirstName(){
		return StringUtil.getStringValue(
		userBean.getFirstName());

	}
	
					public void setLastName(String obj){

		userBean.setLastName(new String(obj));

	}

	public String getLastName(){
		return StringUtil.getStringValue(
		userBean.getLastName());

	}
	
					public void setEmail(String obj){

		userBean.setEmail(new String(obj));

	}

	public String getEmail(){
		return StringUtil.getStringValue(
		userBean.getEmail());

	}
	
					public void setTelephone(String obj){

		userBean.setTelephone(new String(obj));

	}

	public String getTelephone(){
		return StringUtil.getStringValue(
		userBean.getTelephone());

	}
	
					public void setMobilePhone(String obj){

		userBean.setMobilePhone(new String(obj));

	}

	public String getMobilePhone(){
		return StringUtil.getStringValue(
		userBean.getMobilePhone());

	}
	
					public void setTelephoneExt(String obj){

		userBean.setTelephoneExt(new String(obj));

	}

	public String getTelephoneExt(){
		return StringUtil.getStringValue(
		userBean.getTelephoneExt());

	}
	
					public void setDescription(String obj){

		userBean.setDescription(new String(obj));

	}

	public String getDescription(){
		return StringUtil.getStringValue(
		userBean.getDescription());

	}
	
					public void setCreatedBy(String obj){

		userBean.setCreatedBy(new String(obj));

	}

	public String getCreatedBy(){
		return StringUtil.getStringValue(
		userBean.getCreatedBy());

	}
	
				
	public void setCreatedTime(String obj){

		userBean.setCreatedTime(java.sql.Timestamp.valueOf(obj));

	}

	public String getCreatedTime(){
		return StringUtil.getStringValue(
		userBean.getCreatedTime());

	}

	
					public void setModifiedBy(String obj){

		userBean.setModifiedBy(new String(obj));

	}

	public String getModifiedBy(){
		return StringUtil.getStringValue(
		userBean.getModifiedBy());

	}
	
				
	public void setModifiedTime(String obj){

		userBean.setModifiedTime(java.sql.Timestamp.valueOf(obj));

	}

	public String getModifiedTime(){
		return StringUtil.getStringValue(
		userBean.getModifiedTime());

	}

	
					public void setDeletedBy(String obj){

		userBean.setDeletedBy(new String(obj));

	}

	public String getDeletedBy(){
		return StringUtil.getStringValue(
		userBean.getDeletedBy());

	}
	
				
	public void setDeletedTime(String obj){

		userBean.setDeletedTime(java.sql.Timestamp.valueOf(obj));

	}

	public String getDeletedTime(){
		return StringUtil.getStringValue(
		userBean.getDeletedTime());

	}

	
				
	public void setDeletedStatus(String obj){

		userBean.setDeletedStatus(StringUtil.getIntegerValue(obj,0));

	}

	public String getDeletedStatus(){
		return StringUtil.getStringValue(
		userBean.getDeletedStatus());

	}
	
				
	public void setStatus(SubscriptionStatus obj){

		userBean.setStatus(obj);

	}

	public SubscriptionStatus getStatus(){
		return 
		userBean.getStatus();

	}
	
		

	// foreign affairs
	
	

	
	public void setRoleId(Role obj){
		
		userBean.setRoleId(obj);

	}

	public Role getRoleId(){
		return userBean.getRoleId();

	}
	//---
		// -- foreign affairs end
	public String getConfirmPassword() {
		return confirmPassword;
	}
	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}
	public User getUserBean() {
		return userBean;
	}
	public void setUserBean(User userBean) {
		this.userBean = userBean;

	}
	
	public void setUserType (String userType){
		if (userType != null && !userType.equalsIgnoreCase("")){
			this.userBean.setUserType(Integer.valueOf(userType));
		}
		else {
			this.userBean.setUserType(Integer.valueOf(2));
		}
	}
	public String getUserType (){
		String result = "";
		
		if (userBean.getUserType() != null){
			result = userBean.getUserType() + "";
		}
		
		return result;
	}
	public Integer getInstitutionId() {
		return institutionId;
	}
	public void setInstitutionId(Integer institutionId) {
		this.institutionId = institutionId;
	}
	public String getInstitutionName() {
		return institutionName;
	}
	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}
	
	

// class+ 

// class- 
}

src/com/ametis/cms/web/controller/UserController.java
package com.ametis.cms.web.controller;

import java.io.IOException;
import java.util.Collection;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.springframework.context.support.ResourceBundleMessageSource;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
import org.springframework.web.servlet.view.RedirectView;

import com.ametis.cms.datamodel.ActionUser;
import com.ametis.cms.datamodel.Configuration;
import com.ametis.cms.datamodel.Role;
import com.ametis.cms.datamodel.User;
import com.ametis.cms.service.ActivityLogService;
import com.ametis.cms.service.ConfigurationService;
import com.ametis.cms.service.SecurityService;
import com.ametis.cms.service.UserService;
import com.ametis.cms.util.SecurityUtil;
import com.ametis.cms.util.WebUtil;
import com.ametis.cms.util.servlet.TableRenderingServlet;

// imports+ 

// imports- 

/**
 * User is a servlet controller for user Table. All you have to do is to convert
 * necessary data field to the named parameter
 */
public class UserController implements Controller

// extends+

// extends-

{

	private UserService userService;

	private SecurityService securityService;

	private ConfigurationService configurationService;
	private ResourceBundleMessageSource alertProperties;

	private Integer countSet;

	private Integer maxPercountSet;

private ActivityLogService logService;

	
	
	public ActivityLogService getLogService() {
		return logService;
	}

	public void setLogService(ActivityLogService logService) {
		this.logService = logService;
	}
	public ConfigurationService getConfigurationService() {
		return configurationService;
	}

	public void setConfigurationService(ConfigurationService configurationService) {
		this.configurationService = configurationService;
	}

	public SecurityService getSecurityService() {
		return securityService;
	}

	public void setSecurityService(SecurityService securityService) {
		this.securityService = securityService;
	}

	public void setCountSet(Integer countSet) {
		this.countSet = countSet;
	}

	public Integer getCountSet() {
		return this.countSet;
	}

	public void setMaxPercountSet(Integer maxCount) {
		this.maxPercountSet = maxCount;
	}

	public Integer getMaxPercountSet() {
		return this.maxPercountSet;
	}

	public void setAlertProperties(ResourceBundleMessageSource alert) {
		this.alertProperties = alert;
	}

	public ResourceBundleMessageSource getAlertProperties() {
		return alertProperties;
	}

	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	public UserService getUserService() {
		return this.userService;
	}

	public ModelAndView deletePerformed(HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		ModelAndView result = null;

		try {
			Integer userId = WebUtil.getParameterInteger(request, "userId");

			/*
			 * Pkey ini merupakan representasi dari primary key, misalkan hasil
			 * get dari attribute diatas ^ itu cuma ada 1 key saja berarti
			 * tinggal pkey = <nama var diatas> tapi kalau misalkan composite
			 * primary key berarti tinggal bikin representasi primary key nya
			 * saja .
			 */
			java.io.Serializable pkey = userId;

			ActionUser user= securityService.getActionUser(request); 
			
			boolean isUserAuthorized = securityService.isUserAuthorized(user, "DELETEUSER");
			
			if (!isUserAuthorized){
				
				ModelAndView errorResult = new ModelAndView(new RedirectView("errorpage"));	errorResult.addObject("errorType","accessDenied");			
				errorResult.addObject("errorMessage", "You Are Not Authorized for DELETEUSER access");
				return errorResult;
				
			}
			User res = userService.delete(pkey, user);

			if (res != null) {
				request.setAttribute("alert", alertProperties.getMessage(
						"success.delete.user", null, "success", Locale
								.getDefault()));
			} else {
				request.setAttribute("alert", alertProperties.getMessage(
						"fail.delete.user", null, "fail", Locale.getDefault()));

			}
			result = searchPerformed(request, response, "searchUser");
		} catch (Exception e) {
			// nanti kalo sudah OK codenya e.printStackTrace nya di hapus saja
			e.printStackTrace();
			request.setAttribute("alert", alertProperties.getMessage(
					"system.error " + e.getMessage(), null, "fail", Locale
							.getDefault()));
			result = new ModelAndView("error");
		}
		return result;
	}

	public ModelAndView detailPerformed(HttpServletRequest request,
			HttpServletResponse response, String location) throws Exception {
		ModelAndView result = null;

		try {
			
			ActionUser user= securityService.getActionUser(request); 
			
			boolean isUserAuthorized = securityService.isUserAuthorized(user, "DETAILUSER");
			
			if (!isUserAuthorized){
				
				ModelAndView errorResult = new ModelAndView(new RedirectView("errorpage"));	errorResult.addObject("errorType","accessDenied");			
				errorResult.addObject("errorMessage", "You Are Not Authorized for DETAILUSER access");
				return errorResult;
				
			}
			Integer userId = WebUtil.getParameterInteger(request, "userId");

			Integer index = WebUtil.getParameterInteger(request, "index");
			String searchtext = WebUtil.getParameterString(request,
					"searchtext", "");
			String searchby = WebUtil.getParameterString(request, "searchby",
					"");
			/*
			 * Pkey ini merupakan representasi dari primary key, misalkan hasil
			 * get dari attribute diatas ^ itu cuma ada 1 key saja berarti
			 * tinggal pkey = <nama var diatas> tapi kalau misalkan composite
			 * primary key berarti tinggal bikin representasi primary key nya
			 * saja .
			 */

			result = new ModelAndView(location);
			java.io.Serializable pkey = userId;
			User object = userService.get(pkey);

			if (object == null) {
				request.setAttribute("alert", alertProperties.getMessage(
						"not.found.user", null, "fail", Locale.getDefault()));
			}
			/*
			 * convention .. kalo mau nampilkan sebuah object pake BeanClass aja
			 * ya .. ga pake 's' -adhit
			 */

			result.addObject("user", object);
			result.addObject("index", index);
			result.addObject("searchtext", searchtext);
			result.addObject("searchby", searchby);

		} catch (Exception e) {
			e.printStackTrace();
			request.setAttribute("alert", alertProperties.getMessage(
					"system.error " + e.getMessage(), null, "fail", Locale
							.getDefault()));

			result = new ModelAndView("error");
		}

		return result;
	}

	public ModelAndView updateStatusPerformed(HttpServletRequest request,
			HttpServletResponse response, String location) throws Exception {
		ModelAndView result = null;

		try {
			Integer userId = WebUtil.getParameterInteger(request, "userId");

			Integer index = WebUtil.getParameterInteger(request, "index");
			String searchtext = WebUtil.getParameterString(request,
					"searchtext", "");
			String searchby = WebUtil.getParameterString(request, "searchby",
					"");

			String navigation = WebUtil.getParameterString(request,
					"navigation", "");

			ActionUser user= securityService.getActionUser(request); 
			
			boolean isUserAuthorized = securityService.isUserAuthorized(user, "UPDATESTATUSUSER");
			
			if (!isUserAuthorized){
				
				ModelAndView errorResult = new ModelAndView(new RedirectView("errorpage"));	errorResult.addObject("errorType","accessDenied");			
				errorResult.addObject("errorMessage", "You Are Not Authorized for UPDATESTATUSUSER access");
				return errorResult;
				
			}
			/*
			 * Pkey ini merupakan representasi dari primary key, misalkan hasil
			 * get dari attribute diatas ^ itu cuma ada 1 key saja berarti
			 * tinggal pkey = <nama var diatas> tapi kalau misalkan composite
			 * primary key berarti tinggal bikin representasi primary key nya
			 * saja .
			 */

			result = new ModelAndView(location);
			java.io.Serializable pkey = userId;

			if (navigation.equals("activate")) {
				userService.activate(userId, user);
			} else if (navigation.equals("block")) {
				userService.block(userId, user);
			}

			User object = userService.get(pkey);

			if (object == null) {
				request.setAttribute("alert", alertProperties.getMessage(
						"not.found.user", null, "fail", Locale.getDefault()));
			}
			/*
			 * convention .. kalo mau nampilkan sebuah object pake BeanClass aja
			 * ya .. ga pake 's' -adhit
			 */

			result.addObject("user", object);
			result.addObject("index", index);
			result.addObject("searchtext", searchtext);
			result.addObject("searchby", searchby);

		} catch (Exception e) {
			e.printStackTrace();
			request.setAttribute("alert", alertProperties.getMessage(
					"system.error " + e.getMessage(), null, "fail", Locale
							.getDefault()));

			result = new ModelAndView("error");
		}

		return result;
	}

	/* Add by aju on 20150724, for mobile application :D */
	public ModelAndView updateStatusMobilePerformed(HttpServletRequest request,
			HttpServletResponse response, String location) throws Exception {
		ModelAndView result = null;

		try {
			Integer userId = WebUtil.getParameterInteger(request, "userId");
			
			//Add by aju on 20150724, read the token :D
			String mobileToken = WebUtil.getParameterString(request, "mobiletoken", "");
			if(mobileToken.length()>0)
			{
				System.out.println("MobileToken detected on request...");
				String decodedToken = SecurityUtil.saltDecrypt(mobileToken);
				System.out.println("Decoded Token : " + decodedToken);
				if(decodedToken!=mobileToken){
					String[] splitToken = decodedToken.split("&");
					if(splitToken.length>0 && splitToken.length<5){
						userId = Integer.parseInt(splitToken[0].replace("userId=", "") );
						System.out.println("splitDecode=>userId="+userId);
					}
					else{

WebRoot/WEB-INF/jsp/user/accessDenied.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>ACCESS DENIED</title>

</head>
<body>
	<h1>You don't have permission to access this page</h1>
	<h2>If you need access to this page, please contact your IT support</h2>
</body>
</html>

WebRoot/WEB-INF/jsp/user/detailUser.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core_rt" %>
<%@ taglib prefix="spring" uri="/WEB-INF/spring.tld"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt" %>



<form action="user" method="GET" name="form1" id="form_layout">

<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr> 
      <td style="padding-bottom: 2px;">        
        <input title="Edit [Alt+Shift+E]" accesskey="E" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:ubah()" name="Edit" value=" Update " type="button">
        <input title="Delete [Alt+Shift+D]" accesskey="D" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:hapus()" name="Delete" value=" Delete " type="button">        		
        <input title="Change Password [Alt+Shift+P]" accesskey="P" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:changePassword()" name="ChangePasswords" value=" Change Password " type="button">        		        
		<c:if test="${user.status.statusId eq \"1\"}">
			<input title="Block [Alt+Shift+B]" accesskey="B" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:blockUser()" name="block" value=" Block " type="button">        		        
		</c:if>		
		<c:if test="${user.status.statusId eq \"2\"}">
			<input title="Activate [Alt+Shift+A]" accesskey="A" class="ui-button ui-widget ui-state-default ui-corner-all ui-state-focus" onClick="javascript:activateUser()" name="activate" value=" Activate " type="button">        		                
		</c:if>
		</td>
      <td align="right"></td>
    </tr>
  </tbody>
</table>
<table class="tabDetailView" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td colspan="20"  style="padding: 0px;">
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tbody>
				<tr>
					<td style="text-align: left;" class="tabDetailViewDL">&nbsp;

					</td>
					<td class="tabDetailViewDL" align="right" nowrap="nowrap">
						<a href="user?navigation=search&searchtext=<c:out value="${searchtext}"/>&searchby=<c:out value="${searchby}" />&index=<c:out value="${index}" />&index=<c:out value="${index}"/>" class="tabDetailViewDFLink" style="font-weight: normal;">
							<img src="images/back-arrow.png" title="Return to List"/>
						</a>	
					</td>
				</tr>
			</tbody>
		</table>
	  </td>
    </tr>
	<input type="hidden" name="navigation" value="">
	<input type="hidden" name="userId" value="<c:out value="${user.userId}" />">
	
	
		
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Username :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.username}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="15%">Role </td>
	      <td class="tabDetailViewDF" valign="top" width="35%"><c:out value="${user.roleId.roleName}" /></td>
	    </tr>
	
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">First Name :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.firstName}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="17%">Status :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%">
			  <c:if test="${user.status.statusId eq -1}">PENDING</c:if>
			<c:if test="${user.status.statusId eq 1}">ACTIVE</c:if>
			<c:if test="${user.status.statusId eq -3}">PENDING CHANGEPLAN</c:if>
			<c:if test="${user.status.statusId eq -2}">BLOCKED</c:if>
			<c:if test="${user.status.statusId eq 2}">TERMINATED</c:if>
			<c:if test="${user.status.statusId eq 3}">RESIGNED</c:if>
			<c:if test="${user.status.statusId eq 4}">INACTIVE</c:if>
			<c:if test="${user.status.statusId eq 5}">INITIALIZED</c:if></td>
	    </tr>
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Last Name :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.lastName}"/></td>
	       <td class="tabDetailViewDL" valign="top" width="17%">Telephone :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.telephone}"/></td>
	    </tr>
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Email :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.email}"/></td>
   <td class="tabDetailViewDL" valign="top" width="17%">Telephone Ext :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.telephoneExt}"/></td>
	    </tr>
	
	
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="15%"></td>
	      <td class="tabDetailViewDF" valign="top" width="35%"></td>
	      <td class="tabDetailViewDL" valign="top" width="17%">Mobile Phone :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.mobilePhone}"/></td>

	    </tr>
			
	
			
		
	
			
	
			
	
			
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Created Time :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.createdTime}"/>  - <c:out value="${user.createdBy}"/></td>
	      <td class="tabDetailViewDL" valign="top" width="17%">Modified Time :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.modifiedTime}"/> - <c:out value="${user.modifiedBy}"/></td>
	    </tr>
			
	
	
			
	
	    <tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Description :&nbsp;</td>
		  
			 
	      <td class="tabDetailViewDF" valign="top" width="33%" colspan="3"><c:out value="${user.description}"/></td>
	    
	    </tr>
	</tbody>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr> 
      <td style="padding-top: 2px;">        
      
		</td>
      <td align="right"></td>
    </tr>
  </tbody>
</table>
	
</form>
<script language="javascript">
	function hapus (){
	var delConfirm = window.confirm ("Are You Sure Want To Delete This Entry ?");
		if (delConfirm){
			document.form1.navigation.value = "delete";
			document.form1.submit();
		}
	}
	function kembali (){
		document.form1.navigation.value = "back";
		document.form1.submit();
	}
	function changePassword(){
		document.form1.navigation.value = "chpass";
		document.form1.action = "user";
		document.form1.submit();
	}
	function blockUser(){
		document.form1.navigation.value = "block";
		document.form1.action = "user";
		document.form1.submit();
	}
	function activateUser(){
		document.form1.navigation.value = "activate";
		document.form1.action = "user";
		document.form1.submit();
	}
	function ubah (){
		document.form1.navigation.value = "update";
		document.form1.action = "user-form";
		document.form1.method = "GET";
		document.form1.submit();
	}
</script>

WebRoot/WEB-INF/jsp/user/error.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core_rt" %>
<%@ taglib prefix="spring" uri="/WEB-INF/spring.tld"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt" %>



<form action="user" method="GET" name="form1" id="form_layout">
	<input type="hidden" name="navigation" value="">
	<input type="hidden" name="userId" value="<c:out value="${user.userId}" />">

<table class="tabDetailView" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td colspan="20"  style="padding: 0px;">
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tbody>
				<tr>
					<td style="text-align: left;" class="tabDetailViewDL">&nbsp;

					</td>
					<td class="tabDetailViewDL" align="right" nowrap="nowrap">
						<a href="user?navigation=search&searchtext=<c:out value="${searchtext}"/>&searchby=<c:out value="${searchby}" />&index=<c:out value="${index}"/>" class="tabDetailViewDFLink" style="font-weight: normal;">Return to List&nbsp;</a>					
					</td>
				</tr>
			</tbody>
		</table>
	  </td>
    </tr>
	
	
	
	
			
		<tr>
	      <td class="tabDetailViewDL" valign="top" width="17%">Status :&nbsp;</td>
		  
			  <td class="tabDetailViewDF" valign="top" width="33%"><c:out value="${user.status.status}"/></td>
	    </tr>
    <tr>
      <td colspan="20"  style="padding: 0px;">
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tbody>
				<tr>
					<td style="text-align: left;" class="tabDetailViewDL">&nbsp;

					</td>
					<td class="tabDetailViewDL" align="right" nowrap="nowrap">
						<a href="user?navigation=search&searchtext=<c:out value="${searchtext}"/>&searchby=<c:out value="${searchby}" />&index=<c:out value="${index}"/>" class="tabDetailViewDFLink" style="font-weight: normal;">Return to List&nbsp;</a>					
					</td>
				</tr>
			</tbody>
		</table>
	  </td>
    </tr>				
	</tbody>
</table>
	
</form>

WebRoot/WEB-INF/jsp/user/lookupUserJson.jsp
<%@ taglib prefix="json" uri="http://www.atg.com/taglibs/json" %>


<json:array items="${Users}" var="user">
	<json:object>
		<json:property name="id" value="${user.userId}" />
		<json:property name="name" value="${ user.username}" />
	</json:object>




</json:array>